name: coffee_shop_admin
description: Aplikasi admin coffee shop
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Untuk animasi list seperti geser untuk hapus
  flutter_slidable: ^3.0.0

  # Untuk gambar dari assets
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/